INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('USD', '美元');
INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('GBP', '英鎊');
INSERT INTO currency (CURRENCY_CODE, CURRENCY_NAME) VALUES ('EUR', '歐元');